// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  ビルド時の短縮gitコミットハッシュ（`build.rs` が `TSUMUGI_GIT_HASH` として埋め込む）。
	 *  `.git` が無い環境(tarball等)からのビルドでは "unknown" になる。
	 */
	gitCommitHash: () => __TAURI_INVOKE<string>("git_commit_hash"),
	/**
	 *  GitHub Releases から最新版を確認する（Issue #4）。新しいバージョンがあれば返し、
	 *  最新か取得に失敗した場合は None（呼び出し側を静かに無視させ、オフライン時等に
	 *  エラー扱いでBackstageを騒がせないようにする）。
	 */
	checkLatestRelease: () => typedError<{
	version: string,
	url: string,
} | null, Error>(__TAURI_INVOKE("check_latest_release")),
	/**  MiAuth を開始し、認可URLと session_id を返す。 */
	startMiauth: (host: string) => typedError<MiAuthSession, Error>(__TAURI_INVOKE("start_miauth", { host })),
	/**  ブラウザでの認可完了後に呼ぶ。token を keyring に保存し、Account を返す。 */
	completeMiauth: (sessionId: string) => typedError<Account, Error>(__TAURI_INVOKE("complete_miauth", { sessionId })),
	/**  登録済みアカウント一覧。 */
	listAccounts: () => typedError<Account[], Error>(__TAURI_INVOKE("list_accounts")),
	/**  既定アカウントを切り替える。 */
	switchAccount: (accountId: string) => typedError<null, Error>(__TAURI_INVOKE("switch_account", { accountId })),
	/**  アカウント削除（token も keyring から消す）。 */
	removeAccount: (accountId: string) => typedError<null, Error>(__TAURI_INVOKE("remove_account", { accountId })),
	/**  ログアウト（削除と同義: token 破棄 + アカウント除去）。 */
	logout: (accountId: string) => typedError<null, Error>(__TAURI_INVOKE("logout", { accountId })),
	/**  指定アカウントで `/i` を叩き、自分の User を返す。 */
	whoami: (accountId: string) => typedError<User, Error>(__TAURI_INVOKE("whoami", { accountId })),
	/**  タブを新規作成する。`group_id` が None なら新しい視覚カラム(グループ)を作る。 */
	addColumn: (accountId: string, kind: ColumnKind, filter: FilterQuery, groupId: string | null) => typedError<OpenedColumn, Error>(__TAURI_INVOKE("add_column", { accountId, kind, filter, groupId })),
	/**  永続化済みタブを再開する（起動時の復元）。 */
	resumeColumn: (columnId: string) => typedError<OpenedColumn, Error>(__TAURI_INVOKE("resume_column", { columnId })),
	/**  永続化済みグループ一覧。 */
	listGroups: () => typedError<ColumnGroup[], Error>(__TAURI_INVOKE("list_groups")),
	/**  永続化済みタブ一覧。 */
	listColumns: () => typedError<Column[], Error>(__TAURI_INVOKE("list_columns")),
	/**  ローカルDBにキャッシュ済みのノート総数。Backstageのステータス表示用。 */
	noteCount: () => typedError<number, Error>(__TAURI_INVOKE("note_count")),
	/**  投稿日時(epoch秒)が since_epoch_secs 以降のノート件数。Backstageの流速表示用。 */
	notesSince: (sinceEpochSecs: number) => typedError<number, Error>(__TAURI_INVOKE("notes_since", { sinceEpochSecs })),
	/**
	 *  設定（表示→ノートキャッシュの上限）に従ってキャッシュから古いノートを削除する（Issue #6）。
	 *  上限0なら無制限で何もしない。実際に削除した件数を返す。
	 */
	pruneNoteCache: () => typedError<number, Error>(__TAURI_INVOKE("prune_note_cache")),
	/**  過去ページ（上スクロール）。 */
	fetchBackfill: (columnId: string, untilId: string) => typedError<Note[], Error>(__TAURI_INVOKE("fetch_backfill", { columnId, untilId })),
	/**  通知カラムの過去ページ。 */
	fetchNotificationsBackfill: (columnId: string, untilId: string) => typedError<Notification[], Error>(__TAURI_INVOKE("fetch_notifications_backfill", { columnId, untilId })),
	/**  タブを閉じる（購読解除＋永続層から削除＋空グループ掃除）。 */
	closeColumn: (columnId: string) => typedError<null, Error>(__TAURI_INVOKE("close_column", { columnId })),
	/**  グループ幅を更新（永続化）。 */
	setGroupWidth: (groupId: string, width: number) => typedError<null, Error>(__TAURI_INVOKE("set_group_width", { groupId, width })),
	/**  グループの幅モード（固定/自動調整）を更新。 */
	setGroupAuto: (groupId: string, auto: boolean) => typedError<null, Error>(__TAURI_INVOKE("set_group_auto", { groupId, auto })),
	/**  グループ(視覚カラム)の並び順を更新。 */
	reorderGroups: (orderedIds: string[]) => typedError<null, Error>(__TAURI_INVOKE("reorder_groups", { orderedIds })),
	/**
	 *  タブを別グループへ移動し、そのグループ内順序を更新（並べ替え兼移動）。
	 *  `ordered_tab_ids` は移動先グループのタブを希望順に並べた id 列。
	 */
	moveTab: (tabId: string, groupId: string, orderedTabIds: string[]) => typedError<null, Error>(__TAURI_INVOKE("move_tab", { tabId, groupId, orderedTabIds })),
	/**  表示中ノートをキャプチャ購読する。 */
	captureNotes: (columnId: string, noteIds: string[]) => typedError<null, Error>(__TAURI_INVOKE("capture_notes", { columnId, noteIds })),
	/**  キャプチャ解除。 */
	uncaptureNotes: (columnId: string, noteIds: string[]) => typedError<null, Error>(__TAURI_INVOKE("uncapture_notes", { columnId, noteIds })),
	/**  フィルタ（TQL/キーワード）の妥当性検証。 */
	validateFilter: (filter: FilterQuery) => typedError<null, Error>(__TAURI_INVOKE("validate_filter", { filter })),
	/**
	 *  エキスパートモード用: `from <sources> where <expr>` 全文の構文検証のみ行う。
	 *  list/antenna/channel の id 存在確認や user acct 解決は行わない（実際の解決はカラム作成時）。
	 */
	validateTqlQuery: (text: string) => typedError<null, Error>(__TAURI_INVOKE("validate_tql_query", { text })),
	/**  ユーザリスト一覧（List タブ作成用）。 */
	listUserLists: (accountId: string) => typedError<UserList[], Error>(__TAURI_INVOKE("list_user_lists", { accountId })),
	/**  アンテナ一覧（Antenna タブ作成用）。 */
	listAntennas: (accountId: string) => typedError<SourceItem[], Error>(__TAURI_INVOKE("list_antennas", { accountId })),
	/**  フォロー中チャンネル一覧（Channel タブ作成用）。 */
	listChannels: (accountId: string) => typedError<SourceItem[], Error>(__TAURI_INVOKE("list_channels", { accountId })),
	/**  acct から User を解決（User タブ作成用）。 */
	resolveUserAcct: (accountId: string, acct: string) => typedError<User, Error>(__TAURI_INVOKE("resolve_user_acct", { accountId, acct })),
	/**  タブ名を変更する（空文字/None で自動生成名に戻す）。 */
	renameColumn: (columnId: string, title: string | null) => typedError<null, Error>(__TAURI_INVOKE("rename_column", { columnId, title })),
	/**
	 *  タブごとの通知可否・通知音の選択を変更する。ストリームは張り直さない軽量操作。
	 *  notify_sound_choice は空文字ならグローバル設定を継承する。
	 */
	setColumnNotify: (columnId: string, notifyDesktop: boolean, notifySound: boolean, notifySoundChoice: string) => typedError<null, Error>(__TAURI_INVOKE("set_column_notify", { columnId, notifyDesktop, notifySound, notifySoundChoice })),
	/**
	 *  既存タブのソース種別・フィルタ・名前を変更し、ストリームを張り直す。
	 *  アカウントは変更しない。フィルタ変更でキャッシュが不整合になるためクリアして再取得する。
	 */
	updateColumn: (columnId: string, kind: ColumnKind, filter: FilterQuery, title: string | null) => typedError<OpenedColumn, Error>(__TAURI_INVOKE("update_column", { columnId, kind, filter, title })),
	/**  投稿する（本文・CW・可視性・添付・投票・返信/引用/Renote）。作成された Note を返す。 */
	postNote: (accountId: string, draft: NoteDraft_Deserialize) => typedError<Note, Error>(__TAURI_INVOKE("post_note", { accountId, draft })),
	/**  純粋 Renote。 */
	renote: (accountId: string, noteId: string, visibility: VisibilityInput) => typedError<Note, Error>(__TAURI_INVOKE("renote", { accountId, noteId, visibility })),
	/**  ノート削除。 */
	deleteNoteCmd: (accountId: string, noteId: string) => typedError<null, Error>(__TAURI_INVOKE("delete_note_cmd", { accountId, noteId })),
	/**  リアクション付与（カスタム絵文字は `:name:` / `:name@host:`、Unicode は生文字）。 */
	react: (accountId: string, noteId: string, reaction: string) => typedError<null, Error>(__TAURI_INVOKE("react", { accountId, noteId, reaction })),
	/**  リアクション解除。 */
	unreact: (accountId: string, noteId: string) => typedError<null, Error>(__TAURI_INVOKE("unreact", { accountId, noteId })),
	/**  アンケートに投票する（choice は 0-based index）。 */
	votePoll: (accountId: string, noteId: string, choice: number) => typedError<null, Error>(__TAURI_INVOKE("vote_poll", { accountId, noteId, choice })),
	/**  カスタム絵文字一覧（リアクションピッカー用）。host 単位でキャッシュする。 */
	listCustomEmojis: (accountId: string) => typedError<EmojiDef[], Error>(__TAURI_INVOKE("list_custom_emojis", { accountId })),
	/**  ローカルファイルをドライブへアップロードし、DriveFile を返す（投稿添付用）。 */
	uploadFile: (accountId: string, path: string) => typedError<DriveFile, Error>(__TAURI_INVOKE("upload_file", { accountId, path })),
	saveUrlToFile: (url: string, path: string) => typedError<null, Error>(__TAURI_INVOKE("save_url_to_file", { url, path })),
	/**  現在の NG 設定を取得。 */
	getMute: () => typedError<MuteConfig, Error>(__TAURI_INVOKE("get_mute")),
	/**  NG 設定を更新（永続化＋以降の受信に即反映）。 */
	setMute: (config: MuteConfig) => typedError<null, Error>(__TAURI_INVOKE("set_mute", { config })),
	/**  デスクトップ通知・音の設定を取得。 */
	getNotify: () => typedError<NotifyConfig, Error>(__TAURI_INVOKE("get_notify")),
	/**  デスクトップ通知・音の設定を更新（永続化）。 */
	setNotify: (config: NotifyConfig) => typedError<null, Error>(__TAURI_INVOKE("set_notify", { config })),
	/**  表示設定（テーマ・既定カラム幅）を取得。 */
	getUiPrefs: () => typedError<UiPrefs, Error>(__TAURI_INVOKE("get_ui_prefs")),
	/**  表示設定を更新（永続化）。 */
	setUiPrefs: (prefs: UiPrefs) => typedError<null, Error>(__TAURI_INVOKE("set_ui_prefs", { prefs })),
	/**
	 *  ローカル画像ファイルを data URL(base64)へ変換する（背景画像設定用）。
	 *  UiPrefs.background_image に直接保存できる形にする。拡張子から MIME を推定する。
	 */
	readImageDataUrl: (path: string) => typedError<string, Error>(__TAURI_INVOKE("read_image_data_url", { path })),
	/**  ローカル音声ファイルを data URL(base64)へ変換する（通知音設定用）。 */
	readAudioDataUrl: (path: string) => typedError<string, Error>(__TAURI_INVOKE("read_audio_data_url", { path })),
	/**
	 *  サーバ側のミュート/ブロックを取得して AppState に反映する。返り値は対象ユーザ数。
	 *  起動時とアカウント追加時にフロントから呼ぶ（Krile MuteBlockManager 相当）。
	 */
	syncServerMutes: (accountId: string) => typedError<number, Error>(__TAURI_INVOKE("sync_server_mutes", { accountId })),
};

/** Events */
export const events = {
	columnConnectionState: makeEvent<ColumnConnectionState>("column-connection-state"),
	columnGapFill: makeEvent<ColumnGapFill>("column-gap-fill"),
	columnNote: makeEvent<ColumnNote>("column-note"),
	columnNoteUpdated: makeEvent<ColumnNoteUpdated>("column-note-updated"),
	columnNotification: makeEvent<ColumnNotification>("column-notification"),
};

/* Types */
/**
 *  設計書§5。**token 本体は含めない**（keyring に保管し Core 内のみで扱う）。
 *  フロントへ token を渡す command は設けない。
 */
export type Account = {
	/**  アプリ内部で発行する UUID（keyring のキーにも使う） */
	id: string,
	/**  例 "misskey.io" */
	host: string,
	/**  ログインユーザ名（@なし） */
	username: string,
	/**  インスタンス上の userId（mine / to_me 判定に使う） */
	userId: string,
	displayName: string,
	avatarUrl: string | null,
};

/**  タブ = 受信ソース + フィルタ（1タイムライン）。視覚的なカラム(ColumnGroup)に属する。 */
export type Column = {
	id: string,
	accountId: string,
	kind: ColumnKind,
	/**  グループ内のタブ順 */
	order: number,
	filter: FilterQuery,
	notifySound: boolean,
	notifyDesktop: boolean,
	/**  このタブの通知音（プリセットIDまたはdata URL）。空文字なら設定→通知のグローバル選択を継承する。 */
	notifySoundChoice: string,
	/**  所属する視覚カラム(ColumnGroup)の id */
	groupId: string,
	/**  ユーザ設定のタブ名。None なら種別から自動生成した名前を使う。 */
	title: string | null,
};

/**  カラムの接続状態（UI 表示用）。 */
export type ColumnConnectionState = {
	columnId: string,
	state: ConnectionState,
};

/**  起動時のギャップ埋め結果をまとめて反映する（通知は鳴らさない・出入りの都度イベントにしない）。 */
export type ColumnGapFill = {
	columnId: string,
	notes: Note[],
};

/**  視覚的なカラム（タブの集合）。幅と並び順を持つ。 */
export type ColumnGroup = {
	id: string,
	order: number,
	width: number,
	/**  true なら幅固定ではなくウィンドウ幅に応じて自動調整(flex)する */
	auto: boolean,
};

/**  設計書§8.2 の MVP スコープ。Antenna/Channel/User/Tag/Cache は将来拡張（TQL §2）。 */
export type ColumnKind = { type: "home" } | { type: "local" } | { type: "global" } | { type: "hybrid" } | { type: "notifications" } | { type: "list"; listId: string } | { type: "search"; query: string } | { type: "antenna"; antennaId: string } | { type: "channel"; channelId: string } | { type: "user"; userId: string } | { type: "tag"; tag: string } | 
/**
 *  エキスパートモード: TQL の `from <sources> where <expr>` 全文で複数ソースを合成する。
 *  実ソースは filter(FilterQuery::Tql の全文)を都度パースして得る（kind 自体に持たない）。
 */
{ type: "tql" };

/**  カラムに新規ノートを追加する（フィルタ通過済み）。 */
export type ColumnNote = {
	columnId: string,
	note: Note,
};

/**
 *  キャプチャ中ノートの更新（他者のリアクション/投票/削除）。値のみ更新し、
 *  カラムからの出入りはしない（TQL§6 の方針）。
 */
export type ColumnNoteUpdated = {
	columnId: string,
	noteId: string,
	update: NoteUpdate,
	/**  更新を起こしたユーザ（自分の操作は楽観的更新済みなのでフロントで無視するため） */
	actorId: string | null,
};

/**  通知カラムに新規通知を追加する。 */
export type ColumnNotification = {
	columnId: string,
	notification: Notification,
};

export type ConnectionState = "connecting" | "connected" | "reconnecting" | "error";

/**  ユーザーが作成したカスタムテーマ。 */
export type CustomTheme = {
	id: string,
	name: string,
	colors: ThemeColors,
};

export type DriveFile = {
	id: string,
	/**  "image/png" 等。file_types はここから category 化 */
	mimeType: string,
	isSensitive: boolean,
	url: string,
	thumbnailUrl: string | null,
	/**  元のファイル名（メディア以外はダウンロードリンクの表示名に使う） */
	name?: string,
};

/**
 *  リアクションピッカー用の絵文字定義（インスタンス単位でキャッシュ）。
 *  注意: `Note.reactions` は「絵文字キー→集計数」であり、誰がリアクションしたかは
 *  Misskey は返さない（docs/filter-dsl-design.md §3.4）。
 */
export type EmojiDef = {
	/**  "blobcat"（: なし） */
	name: string,
	/**  None=ローカル */
	host: string | null,
	url: string,
	category: string | null,
	aliases: string[],
};

export type Error = 
/**  ネットワーク到達不可・タイムアウト等 */
{ kind: "network"; message: string } | 
/**  認証失敗・トークン無効（HTTP 401 / Misskey の認証系エラー） */
{ kind: "unauthorized"; message: string } | 
/**  権限不足（HTTP 403） */
{ kind: "forbidden"; message: string } | 
/**  レート制限（HTTP 429） */
{ kind: "rateLimited" } | 
/**  リソースが存在しない（HTTP 404 / Misskey NO_SUCH_*） */
{ kind: "notFound"; message: string } | 
/**  上記以外の Misskey API エラー（endpoint と Misskey エラーコードを含める） */
{ kind: "api"; message: string } | 
/**  keyring 等シークレットストアの失敗 */
{ kind: "secret"; message: string } | 
/**  ローカル DB（SQLite）の失敗 */
{ kind: "db"; message: string } | 
/**  入力・状態の不整合（未知の session_id、未登録アカウント等） */
{ kind: "invalid"; message: string };

/**  MVP=Keywords のみ。Phase 4 で Tql を有効化（filter/ast.rs の Query を保持）。 */
export type FilterQuery = 
/**  部分一致キーワード（OR）。空 Vec = 素通し。 */
{ kind: "keywords"; value: string[] } | 
/**  Phase 4: TQL クエリ文字列（保存形）。 */
{ kind: "tql"; value: string };

export type LatestRelease = {
	version: string,
	url: string,
};

/**  `start_miauth` の戻り値。フロントは `url` をブラウザで開く。 */
export type MiAuthSession = {
	url: string,
	sessionId: string,
};

/**  ローカル NG（ミュート）設定。サーバの mute/block とは別の、クライアント側フィルタ。 */
export type MuteConfig = {
	/**  本文/CW に含まれると非表示にする語（部分一致・大文字小文字無視） */
	ngWords: string[],
	/**  非表示にするユーザ（`@user@host` 形式。`@` は省略可） */
	ngUsers: string[],
	/**  非表示にするインスタンス（host。例: example.com） */
	ngInstances: string[],
};

/**  docs/filter-dsl-design.md §7 / 設計書§5.1。フィルタ評価の対象そのもの。 */
export type Note = {
	/**  aid/aidx。数値比較しない */
	id: string,
	/**  epoch秒。時間比較はこれ。TS へは number で出す（2^53 に収まり精度損失なし） */
	createdAt: number,
	/**  MFM原文。純Renoteは None */
	text: string | null,
	cw: string | null,
	visibility: Visibility,
	localOnly: boolean,
	user: User,
	replyId: string | null,
	renoteId: string | null,
	/**  引用/Renote先（浅く保持） */
	renote: Note | null,
	files: DriveFile[],
	poll: Poll | null,
	tags: string[],
	/**  メンション先 userId */
	mentions: string[],
	/**  カスタム絵文字 name -> url（本文 MFM の `:name:` とリアクション絵文字の描画に使う） */
	emojis: { [key in string]: string },
	channelId: string | null,
	via: string | null,
	lang: string | null,
	/**  キー=Misskey形式（Unicode生 or :name@host:） */
	reactions: { [key in string]: number },
	reactionCount: number,
	renoteCount: number,
	replyCount: number,
	myReaction: string | null,
	isRenotedByMe: boolean,
	isFavoritedByMe: boolean,
	isPinned: boolean,
};

/**  `notes/create` 等の入力。フロントの NoteDraft をそのまま受ける想定。 */
export type NoteDraft = NoteDraft_Serialize | NoteDraft_Deserialize;

/**  `notes/create` 等の入力。フロントの NoteDraft をそのまま受ける想定。 */
export type NoteDraft_Deserialize = {
	text: string | null,
	cw: string | null,
	visibility: VisibilityInput,
	fileIds: string[],
	poll: PollInput_Deserialize | null,
	replyId: string | null,
	renoteId: string | null,
	localOnly?: boolean,
};

/**  `notes/create` 等の入力。フロントの NoteDraft をそのまま受ける想定。 */
export type NoteDraft_Serialize = {
	text?: string | null,
	cw?: string | null,
	visibility: VisibilityInput,
	fileIds?: string[],
	poll?: PollInput_Serialize | null,
	replyId?: string | null,
	renoteId?: string | null,
	localOnly: boolean,
};

export type NoteUpdate = { type: "reacted"; reaction: string } | { type: "unreacted"; reaction: string } | { type: "pollVoted"; choice: number } | { type: "deleted" };

/**  通知（Notifications カラム用）。Note とは別物で、フォロー/メンション/リアクション等を表す。 */
export type Notification = {
	id: string,
	/**  epoch秒 */
	createdAt: number,
	/**
	 *  種別: follow / mention / reply / renote / quote / reaction / pollEnded /
	 *  receiveFollowRequest / followRequestAccepted / achievementEarned / app 等
	 */
	type: string,
	/**  通知を起こしたユーザ（follow/reaction 等） */
	user: User | null,
	/**  対象ノート（mention/reply/renote/quote/reaction/pollEnded） */
	note: Note | null,
	/**  リアクション種別（kind == "reaction" のとき） */
	reaction: string | null,
};

/**  デスクトップ通知・通知音の設定（グローバル）。通知カラムに新着が来たとき使う。 */
export type NotifyConfig = {
	/**  OS のデスクトップ通知を出す */
	desktop: boolean,
	/**  通知音を鳴らす */
	sound: boolean,
	/**
	 *  通知音の選択。プリセットID("beep"/"chime"/"ping"/"pop")か、data URL(カスタム音声ファイル)。
	 *  空文字なら既定プリセット("beep")を使う。タブ側で個別指定が無い場合のフォールバック。
	 */
	soundChoice?: string,
};

/**  タブを開いた結果。所属グループも返す（新規グループの幅などをフロントへ）。 */
export type OpenedColumn = {
	column: Column,
	group: ColumnGroup,
	notes: Note[],
	notifications: Notification[],
};

export type Poll = {
	choices: PollChoice[],
	multiple: boolean,
	expiresAt: number | null,
};

export type PollChoice = {
	text: string,
	votes: number,
	isVoted: boolean,
};

export type PollInput = PollInput_Serialize | PollInput_Deserialize;

export type PollInput_Deserialize = {
	choices: string[],
	multiple?: boolean,
	expiresAt: number | null,
};

export type PollInput_Serialize = {
	choices: string[],
	multiple: boolean,
	expiresAt?: number | null,
};

/**  id + 表示名の軽量参照（アンテナ/チャンネル等のソース選択用）。 */
export type SourceItem = {
	id: string,
	name: string,
};

/**  テーマ1個分の配色（app.css の CSS変数9個に対応）。 */
export type ThemeColors = {
	surface1: string,
	surface2: string,
	surface3: string,
	border: string,
	text: string,
	textDim: string,
	accent: string,
	/**  成功/肯定的な意味の強調色（例: Renoteバナー）。追加前のカスタムテーマ読み込み用に既定値を持つ。 */
	success?: string,
	/**  情報的な意味の強調色（例: リプライバナー）。追加前のカスタムテーマ読み込み用に既定値を持つ。 */
	info?: string,
};

/**  表示まわりのグローバル設定。テーマ・新規カラムの既定幅・キーバインド上書き・フォント・背景。 */
export type UiPrefs = {
	/**  "auto" | "light" | "dark" | "preset:<id>"(フロント側定義) | "custom:<CustomTheme.id>" */
	theme: string,
	/**  新規カラム（グループ）作成時の既定幅（px） */
	defaultColumnWidth: number,
	/**
	 *  キーバインドの上書き（action -> chord）。空なら既定を使う。
	 *  中身の解釈はフロント（lib/keymap）に委ねる（Rust からは不透明に永続化）。
	 */
	keymap?: { [key in string]: string },
	/**
	 *  CSS font-family 値をそのまま保持（例 `"Cascadia Code", monospace`）。
	 *  空文字なら既定フォントスタックを使う。
	 */
	fontFamily?: string,
	/**  背景画像を data URL(base64)でそのまま保持。空文字なら背景画像なし。 */
	backgroundImage?: string,
	/**  背景に乗せる黒オーバーレイの濃さ（0〜100%）。可読性確保用。 */
	backgroundDim?: number,
	/**  背景画像のぼかし量（px, 0〜40）。 */
	backgroundBlur?: number,
	/**  カラム背景の不透明度（60〜100%）。背景画像を透けさせる。 */
	columnOpacity?: number,
	/**  既定アカウントの id。空文字なら未設定（アカウント一覧の先頭を使う）。 */
	defaultAccountId?: string,
	/**  Unicode絵文字の表示スタイル。"native" | "twemoji" | "fluentEmoji"（本家 emojiStyle 準拠）。 */
	emojiStyle?: string,
	/**
	 *  起動時、キャッシュに無い間(閉じていた間)のノートをRESTで遡って埋める件数の上限。
	 *  0 なら無効（従来どおりキャッシュのみ表示）。
	 */
	gapFillLimit?: number,
	/**  ユーザーが作成したカスタムテーマの一覧。 */
	customThemes?: CustomTheme[],
	/**
	 *  メディア添付ノートのサムネイル高さ上限（px）。ノートを詰めたい人は小さく、
	 *  大きく見たい人は大きくできるようにする。
	 */
	mediaThumbnailHeight?: number,
	/**
	 *  ローカルキャッシュに保持するノート件数の上限。超えた分は古い順に削除する
	 *  （Issue #6: 無制限に溜まり続けないようにする）。0 なら無制限。
	 */
	noteCacheLimit?: number,
	/**
	 *  ローカルキャッシュに保持するノートの経過日数上限。created_at がこれより古いノートは
	 *  削除する。0 なら無制限。
	 */
	noteCacheMaxAgeDays?: number,
	/**  ローカルキャッシュDBのサイズ上限（MB）。超えている間は古い順に削除し続ける。0 なら無制限。 */
	noteCacheMaxSizeMb?: number,
};

/**  docs/filter-dsl-design.md §7。`host` が None ならローカルユーザ。 */
export type User = {
	id: string,
	/**  @なしのユーザ名 */
	username: string,
	/**  None=ローカル */
	host: string | null,
	/**  表示名 */
	name: string | null,
	avatarUrl: string | null,
	isBot: boolean,
	isCat: boolean,
	followersCount: number,
	followingCount: number,
	notesCount: number,
	/**
	 *  表示名(`name`)中のカスタム絵文字ショートコード解決用 {name: url}。
	 *  既存キャッシュ済みJSON(このフィールド追加前に保存されたもの)との後方互換のため default。
	 */
	emojis?: { [key in string]: string },
};

/**  ユーザリスト（List カラムのソース選択用）。 */
export type UserList = {
	id: string,
	name: string,
};

/**  Specified = direct */
export type Visibility = "public" | "home" | "followers" | "specified";

export type VisibilityInput = "public" | "home" | "followers" | 
/**  direct（Misskey では specified） */
"specified";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

