// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  MiAuth を開始し、認可URLと session_id を返す。 */
	startMiauth: (host: string) => typedError<MiAuthSession, Error>(__TAURI_INVOKE("start_miauth", { host })),
	/**  ブラウザでの認可完了後に呼ぶ。token を keyring に保存し、Account を返す。 */
	completeMiauth: (sessionId: string) => typedError<Account, Error>(__TAURI_INVOKE("complete_miauth", { sessionId })),
	/**  登録済みアカウント一覧。 */
	listAccounts: () => typedError<Account[], Error>(__TAURI_INVOKE("list_accounts")),
	/**  既定アカウントを切り替える。 */
	switchAccount: (accountId: string) => typedError<null, Error>(__TAURI_INVOKE("switch_account", { accountId })),
	/**  アカウント削除（token も keyring から消す）。 */
	removeAccount: (accountId: string) => typedError<null, Error>(__TAURI_INVOKE("remove_account", { accountId })),
	/**  ログアウト（削除と同義: token 破棄 + アカウント除去）。 */
	logout: (accountId: string) => typedError<null, Error>(__TAURI_INVOKE("logout", { accountId })),
	/**  指定アカウントで `/i` を叩き、自分の User を返す。 */
	whoami: (accountId: string) => typedError<User, Error>(__TAURI_INVOKE("whoami", { accountId })),
};

/* Types */
/**
 *  設計書§5。**token 本体は含めない**（keyring に保管し Core 内のみで扱う）。
 *  フロントへ token を渡す command は設けない。
 */
export type Account = {
	/**  アプリ内部で発行する UUID（keyring のキーにも使う） */
	id: string,
	/**  例 "misskey.io" */
	host: string,
	/**  ログインユーザ名（@なし） */
	username: string,
	/**  インスタンス上の userId（mine / to_me 判定に使う） */
	userId: string,
	displayName: string,
	avatarUrl: string | null,
};

export type Error = 
/**  ネットワーク到達不可・タイムアウト等 */
{ kind: "network"; message: string } | 
/**  認証失敗・トークン無効（HTTP 401 / Misskey の認証系エラー） */
{ kind: "unauthorized"; message: string } | 
/**  権限不足（HTTP 403） */
{ kind: "forbidden"; message: string } | 
/**  レート制限（HTTP 429） */
{ kind: "rateLimited" } | 
/**  リソースが存在しない（HTTP 404 / Misskey NO_SUCH_*） */
{ kind: "notFound"; message: string } | 
/**  上記以外の Misskey API エラー（endpoint と Misskey エラーコードを含める） */
{ kind: "api"; message: string } | 
/**  keyring 等シークレットストアの失敗 */
{ kind: "secret"; message: string } | 
/**  入力・状態の不整合（未知の session_id、未登録アカウント等） */
{ kind: "invalid"; message: string };

/**  `start_miauth` の戻り値。フロントは `url` をブラウザで開く。 */
export type MiAuthSession = {
	url: string,
	sessionId: string,
};

/**  docs/filter-dsl-design.md §7。`host` が None ならローカルユーザ。 */
export type User = {
	id: string,
	/**  @なしのユーザ名 */
	username: string,
	/**  None=ローカル */
	host: string | null,
	/**  表示名 */
	name: string | null,
	avatarUrl: string | null,
	isBot: boolean,
	isCat: boolean,
	followersCount: number,
	followingCount: number,
	notesCount: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

