// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  MiAuth を開始し、認可URLと session_id を返す。 */
	startMiauth: (host: string) => typedError<MiAuthSession, Error>(__TAURI_INVOKE("start_miauth", { host })),
	/**  ブラウザでの認可完了後に呼ぶ。token を keyring に保存し、Account を返す。 */
	completeMiauth: (sessionId: string) => typedError<Account, Error>(__TAURI_INVOKE("complete_miauth", { sessionId })),
	/**  登録済みアカウント一覧。 */
	listAccounts: () => typedError<Account[], Error>(__TAURI_INVOKE("list_accounts")),
	/**  既定アカウントを切り替える。 */
	switchAccount: (accountId: string) => typedError<null, Error>(__TAURI_INVOKE("switch_account", { accountId })),
	/**  アカウント削除（token も keyring から消す）。 */
	removeAccount: (accountId: string) => typedError<null, Error>(__TAURI_INVOKE("remove_account", { accountId })),
	/**  ログアウト（削除と同義: token 破棄 + アカウント除去）。 */
	logout: (accountId: string) => typedError<null, Error>(__TAURI_INVOKE("logout", { accountId })),
	/**  指定アカウントで `/i` を叩き、自分の User を返す。 */
	whoami: (accountId: string) => typedError<User, Error>(__TAURI_INVOKE("whoami", { accountId })),
	/**  カラムを新規作成する。ソース種別＋フィルタを受け、購読を開始する。 */
	addColumn: (accountId: string, kind: ColumnKind, filter: FilterQuery) => typedError<OpenedColumn, Error>(__TAURI_INVOKE("add_column", { accountId, kind, filter })),
	/**  永続化済みカラムを再開する（起動時の復元）。キャッシュ優先で即時表示し購読を張り直す。 */
	resumeColumn: (columnId: string) => typedError<OpenedColumn, Error>(__TAURI_INVOKE("resume_column", { columnId })),
	/**  永続化済みカラム定義の一覧（起動時に取得 → resume_column で復元）。 */
	listColumns: () => typedError<Column[], Error>(__TAURI_INVOKE("list_columns")),
	/**  過去ページ（上スクロール）。カラムのソースから取得し、フィルタ適用＆キャッシュする。 */
	fetchBackfill: (columnId: string, untilId: string) => typedError<Note[], Error>(__TAURI_INVOKE("fetch_backfill", { columnId, untilId })),
	/**  通知カラムの過去ページ。`until_id` より古い通知を返す。 */
	fetchNotificationsBackfill: (columnId: string, untilId: string) => typedError<Notification[], Error>(__TAURI_INVOKE("fetch_notifications_backfill", { columnId, untilId })),
	/**  カラムを閉じる（Streaming 購読解除＋永続層から削除＋キャッシュの所属も掃除）。 */
	closeColumn: (columnId: string) => typedError<null, Error>(__TAURI_INVOKE("close_column", { columnId })),
	/**  カラム幅を更新（永続化）。 */
	setColumnWidth: (columnId: string, width: number) => typedError<null, Error>(__TAURI_INVOKE("set_column_width", { columnId, width })),
	/**  カラムの並び順を更新（与えた id 順に振り直す・永続化）。 */
	reorderColumns: (orderedIds: string[]) => typedError<null, Error>(__TAURI_INVOKE("reorder_columns", { orderedIds })),
	/**  表示中ノートをキャプチャ購読する（他者のリアクション等を追う。初期ページ分をフロントが登録）。 */
	captureNotes: (columnId: string, noteIds: string[]) => typedError<null, Error>(__TAURI_INVOKE("capture_notes", { columnId, noteIds })),
	/**  キャプチャ解除（表示領域外に出たノート）。 */
	uncaptureNotes: (columnId: string, noteIds: string[]) => typedError<null, Error>(__TAURI_INVOKE("uncapture_notes", { columnId, noteIds })),
	/**  フィルタ（TQL/キーワード）の妥当性を検証する（UI の入力チェック用）。 */
	validateFilter: (filter: FilterQuery) => typedError<null, Error>(__TAURI_INVOKE("validate_filter", { filter })),
	/**  自分のユーザリスト一覧（List カラム作成時の選択用）。 */
	listUserLists: (accountId: string) => typedError<UserList[], Error>(__TAURI_INVOKE("list_user_lists", { accountId })),
	/**  投稿する（本文・CW・可視性・添付・投票・返信/引用/Renote）。作成された Note を返す。 */
	postNote: (accountId: string, draft: NoteDraft_Deserialize) => typedError<Note, Error>(__TAURI_INVOKE("post_note", { accountId, draft })),
	/**  純粋 Renote。 */
	renote: (accountId: string, noteId: string, visibility: VisibilityInput) => typedError<Note, Error>(__TAURI_INVOKE("renote", { accountId, noteId, visibility })),
	/**  ノート削除。 */
	deleteNoteCmd: (accountId: string, noteId: string) => typedError<null, Error>(__TAURI_INVOKE("delete_note_cmd", { accountId, noteId })),
	/**  リアクション付与（カスタム絵文字は `:name:` / `:name@host:`、Unicode は生文字）。 */
	react: (accountId: string, noteId: string, reaction: string) => typedError<null, Error>(__TAURI_INVOKE("react", { accountId, noteId, reaction })),
	/**  リアクション解除。 */
	unreact: (accountId: string, noteId: string) => typedError<null, Error>(__TAURI_INVOKE("unreact", { accountId, noteId })),
	/**  カスタム絵文字一覧（リアクションピッカー用）。host 単位でキャッシュする。 */
	listCustomEmojis: (accountId: string) => typedError<EmojiDef[], Error>(__TAURI_INVOKE("list_custom_emojis", { accountId })),
	/**  ローカルファイルをドライブへアップロードし、DriveFile を返す（投稿添付用）。 */
	uploadFile: (accountId: string, path: string) => typedError<DriveFile, Error>(__TAURI_INVOKE("upload_file", { accountId, path })),
};

/** Events */
export const events = {
	columnConnectionState: makeEvent<ColumnConnectionState>("column-connection-state"),
	columnNote: makeEvent<ColumnNote>("column-note"),
	columnNoteUpdated: makeEvent<ColumnNoteUpdated>("column-note-updated"),
	columnNotification: makeEvent<ColumnNotification>("column-notification"),
};

/* Types */
/**
 *  設計書§5。**token 本体は含めない**（keyring に保管し Core 内のみで扱う）。
 *  フロントへ token を渡す command は設けない。
 */
export type Account = {
	/**  アプリ内部で発行する UUID（keyring のキーにも使う） */
	id: string,
	/**  例 "misskey.io" */
	host: string,
	/**  ログインユーザ名（@なし） */
	username: string,
	/**  インスタンス上の userId（mine / to_me 判定に使う） */
	userId: string,
	displayName: string,
	avatarUrl: string | null,
};

/**  カラム = 受信ソース + フィルタ。設計書§5 / phase0-scaffold §2.6。 */
export type Column = {
	id: string,
	accountId: string,
	kind: ColumnKind,
	order: number,
	width: number,
	filter: FilterQuery,
	notifySound: boolean,
	notifyDesktop: boolean,
};

/**  カラムの接続状態（UI 表示用）。 */
export type ColumnConnectionState = {
	columnId: string,
	state: ConnectionState,
};

/**  設計書§8.2 の MVP スコープ。Antenna/Channel/User/Tag/Cache は将来拡張（TQL §2）。 */
export type ColumnKind = { type: "home" } | { type: "local" } | { type: "global" } | { type: "hybrid" } | { type: "notifications" } | { type: "list"; listId: string } | { type: "search"; query: string };

/**  カラムに新規ノートを追加する（フィルタ通過済み）。 */
export type ColumnNote = {
	columnId: string,
	note: Note,
};

/**
 *  キャプチャ中ノートの更新（他者のリアクション/投票/削除）。値のみ更新し、
 *  カラムからの出入りはしない（TQL§6 の方針）。
 */
export type ColumnNoteUpdated = {
	columnId: string,
	noteId: string,
	update: NoteUpdate,
	/**  更新を起こしたユーザ（自分の操作は楽観的更新済みなのでフロントで無視するため） */
	actorId: string | null,
};

/**  通知カラムに新規通知を追加する。 */
export type ColumnNotification = {
	columnId: string,
	notification: Notification,
};

export type ConnectionState = "connecting" | "connected" | "reconnecting" | "error";

export type DriveFile = {
	id: string,
	/**  "image/png" 等。file_types はここから category 化 */
	mimeType: string,
	isSensitive: boolean,
	url: string,
	thumbnailUrl: string | null,
};

/**
 *  リアクションピッカー用の絵文字定義（インスタンス単位でキャッシュ）。
 *  注意: `Note.reactions` は「絵文字キー→集計数」であり、誰がリアクションしたかは
 *  Misskey は返さない（docs/filter-dsl-design.md §3.4）。
 */
export type EmojiDef = {
	/**  "blobcat"（: なし） */
	name: string,
	/**  None=ローカル */
	host: string | null,
	url: string,
	category: string | null,
	aliases: string[],
};

export type Error = 
/**  ネットワーク到達不可・タイムアウト等 */
{ kind: "network"; message: string } | 
/**  認証失敗・トークン無効（HTTP 401 / Misskey の認証系エラー） */
{ kind: "unauthorized"; message: string } | 
/**  権限不足（HTTP 403） */
{ kind: "forbidden"; message: string } | 
/**  レート制限（HTTP 429） */
{ kind: "rateLimited" } | 
/**  リソースが存在しない（HTTP 404 / Misskey NO_SUCH_*） */
{ kind: "notFound"; message: string } | 
/**  上記以外の Misskey API エラー（endpoint と Misskey エラーコードを含める） */
{ kind: "api"; message: string } | 
/**  keyring 等シークレットストアの失敗 */
{ kind: "secret"; message: string } | 
/**  ローカル DB（SQLite）の失敗 */
{ kind: "db"; message: string } | 
/**  入力・状態の不整合（未知の session_id、未登録アカウント等） */
{ kind: "invalid"; message: string };

/**  MVP=Keywords のみ。Phase 4 で Tql を有効化（filter/ast.rs の Query を保持）。 */
export type FilterQuery = 
/**  部分一致キーワード（OR）。空 Vec = 素通し。 */
{ kind: "keywords"; value: string[] } | 
/**  Phase 4: TQL クエリ文字列（保存形）。 */
{ kind: "tql"; value: string };

/**  `start_miauth` の戻り値。フロントは `url` をブラウザで開く。 */
export type MiAuthSession = {
	url: string,
	sessionId: string,
};

/**  docs/filter-dsl-design.md §7 / 設計書§5.1。フィルタ評価の対象そのもの。 */
export type Note = {
	/**  aid/aidx。数値比較しない */
	id: string,
	/**  epoch秒。時間比較はこれ。TS へは number で出す（2^53 に収まり精度損失なし） */
	createdAt: number,
	/**  MFM原文。純Renoteは None */
	text: string | null,
	cw: string | null,
	visibility: Visibility,
	localOnly: boolean,
	user: User,
	replyId: string | null,
	renoteId: string | null,
	/**  引用/Renote先（浅く保持） */
	renote: Note | null,
	files: DriveFile[],
	poll: Poll | null,
	tags: string[],
	/**  メンション先 userId */
	mentions: string[],
	emojis: string[],
	channelId: string | null,
	via: string | null,
	lang: string | null,
	/**  キー=Misskey形式（Unicode生 or :name@host:） */
	reactions: { [key in string]: number },
	reactionCount: number,
	renoteCount: number,
	replyCount: number,
	myReaction: string | null,
	isRenotedByMe: boolean,
	isFavoritedByMe: boolean,
	isPinned: boolean,
};

/**  `notes/create` 等の入力。フロントの NoteDraft をそのまま受ける想定。 */
export type NoteDraft = NoteDraft_Serialize | NoteDraft_Deserialize;

/**  `notes/create` 等の入力。フロントの NoteDraft をそのまま受ける想定。 */
export type NoteDraft_Deserialize = {
	text: string | null,
	cw: string | null,
	visibility: VisibilityInput,
	fileIds: string[],
	poll: PollInput_Deserialize | null,
	replyId: string | null,
	renoteId: string | null,
	localOnly?: boolean,
};

/**  `notes/create` 等の入力。フロントの NoteDraft をそのまま受ける想定。 */
export type NoteDraft_Serialize = {
	text?: string | null,
	cw?: string | null,
	visibility: VisibilityInput,
	fileIds?: string[],
	poll?: PollInput_Serialize | null,
	replyId?: string | null,
	renoteId?: string | null,
	localOnly: boolean,
};

export type NoteUpdate = { type: "reacted"; reaction: string } | { type: "unreacted"; reaction: string } | { type: "pollVoted"; choice: number } | { type: "deleted" };

/**  通知（Notifications カラム用）。Note とは別物で、フォロー/メンション/リアクション等を表す。 */
export type Notification = {
	id: string,
	/**  epoch秒 */
	createdAt: number,
	/**
	 *  種別: follow / mention / reply / renote / quote / reaction / pollEnded /
	 *  receiveFollowRequest / followRequestAccepted / achievementEarned / app 等
	 */
	type: string,
	/**  通知を起こしたユーザ（follow/reaction 等） */
	user: User | null,
	/**  対象ノート（mention/reply/renote/quote/reaction/pollEnded） */
	note: Note | null,
	/**  リアクション種別（kind == "reaction" のとき） */
	reaction: string | null,
};

/**  カラムを開いた結果。ノートカラムは `notes`、通知カラムは `notifications` が入る。 */
export type OpenedColumn = {
	column: Column,
	/**  初期表示用の直近ノート（フィルタ通過済み・新しい順） */
	notes: Note[],
	/**  通知カラムの初期通知（新しい順） */
	notifications: Notification[],
};

export type Poll = {
	choices: PollChoice[],
	multiple: boolean,
	expiresAt: number | null,
};

export type PollChoice = {
	text: string,
	votes: number,
	isVoted: boolean,
};

export type PollInput = PollInput_Serialize | PollInput_Deserialize;

export type PollInput_Deserialize = {
	choices: string[],
	multiple?: boolean,
	expiresAt: number | null,
};

export type PollInput_Serialize = {
	choices: string[],
	multiple: boolean,
	expiresAt?: number | null,
};

/**  docs/filter-dsl-design.md §7。`host` が None ならローカルユーザ。 */
export type User = {
	id: string,
	/**  @なしのユーザ名 */
	username: string,
	/**  None=ローカル */
	host: string | null,
	/**  表示名 */
	name: string | null,
	avatarUrl: string | null,
	isBot: boolean,
	isCat: boolean,
	followersCount: number,
	followingCount: number,
	notesCount: number,
};

/**  ユーザリスト（List カラムのソース選択用）。 */
export type UserList = {
	id: string,
	name: string,
};

/**  Specified = direct */
export type Visibility = "public" | "home" | "followers" | "specified";

export type VisibilityInput = "public" | "home" | "followers" | 
/**  direct（Misskey では specified） */
"specified";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

